import { CheckboxOption } from "@/types";

export const locations =[
  "santa monica",
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "San Francisco",
  "Charlotte",
  "Indianapolis",
  "Seattle",
  "Denver",
  "Washington, D.C.",
  "Boston",
  "El Paso",
  "Nashville",
  "Portland",
  "Las Vegas",
  "Detroit",
  "Oklahoma City",
  "Memphis",
  "Louisville",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Mesa",
  "Kansas City",
  "Atlanta",
  "Long Beach",
  "Omaha",
  "Raleigh",
  "Miami",
  "Colorado Springs",
  "Minneapolis",
  "Tulsa",
  "Cleveland",
  "Wichita",
  "Arlington",
  "New Orleans",
  "Bakersfield",
  "Tampa",
  "Honolulu",
  "Anaheim",
  "Aurora",
  "Santa Ana",
  "St. Louis",
  "Riverside",
  "Corpus Christi",
  "Lexington",
  "Pittsburgh",
  "Anchorage",
  "Stockton",
  "Cincinnati",
  "St. Paul",
  "Toledo",
  "Greensboro",
  "Newark",
  "Plano",
  "Henderson",
  "Lincoln",
  "Orlando",
  "Jersey City",
  "Chula Vista",
  "Buffalo",
  "Fort Wayne",
  "Chandler",
  "St. Petersburg",
  "Laredo",
  "Durham",
  "Irvine",
  "Madison",
  "Norfolk",
  "Lubbock",
  "Gilbert",
  "Winston-Salem",
  "Glendale",
  "Reno",
  "Hialeah",
  "Garland",
  "Scottsdale",
  "Irving",
  "Chesapeake",
  "North Las Vegas",
  "Fremont",
  "Baton Rouge",
  "Richmond",
  "Boise",
  "San Bernardino",
  "Spokane",
  "Montgomery",
  "Des Moines",
  "Modesto",
  "Fayetteville",
  "Tacoma",
  "Shreveport",
  "Fontana",
  "Oxnard",
  "Arlington",
  "Moreno Valley",
  "Akron",
  "Yonkers",
  "Columbus",
  "Augusta",
  "Little Rock",
  "Amarillo",
  "Mobile",
  "Huntington Beach",
  "Glendale",
  "Grand Rapids",
  "Salt Lake City",
  "Tallahassee",
  "Huntsville",
  "Worcester",
  "Knoxville",
  "Grand Prairie",
  "Newport News",
  "Brownsville",
  "Santa Clarita",
  "Overland Park",
  "Providence",
  "Garden Grove",
  "Chattanooga",
  "Oceanside",
  "Jackson",
  "Fort Lauderdale",
  "Santa Rosa",
  "Rancho Cucamonga",
  "Port St. Lucie",
  "Tempe",
  "Ontario",
  "Vancouver",
  "Cape Coral",
  "Sioux Falls",
  "Springfield",
  "Peoria",
  "Pembroke Pines",
  "Elk Grove",
  "Salem",
  "Lancaster",
  "Corona",
  "Eugene",
  "Palmdale",
  "Salinas",
  "Springfield",
  "Pasadena",
  "Fort Collins",
  "Hayward",
  "Pomona",
  "Cary",
  "Rockford",
  "Alexandria",
  "Escondido",
  "McKinney",
  "Kansas City",
  "Joliet",
  "Sunnyvale",
  "Torrance",
  "Bridgeport",
  "Lakewood",
  "Hollywood",
  "Paterson",
  "Naperville",
  "Syracuse",
  "Mesquite",
  "Dayton",
  "Savannah",
  "Clarksville",
  "Orange",
  "Pasadena",
  "Fullerton",
  "Killeen",
  "Frisco",
  "Hampton",
  "McAllen",
  "Warren",
  "Bellevue",
  "West Valley City",
  "Columbia",
  "Olathe",
  "Sterling Heights",
  "New Haven",
  "Miramar",
  "Waco",
  "Thousand Oaks",
  "Cedar Rapids",
  "Charleston",
  "Visalia",
  "Topeka",
  "Elizabeth",
  "Gainesville",
  "Thornton",
  "Roseville",
  "Carrollton",
  "Coral Springs",
  "Stamford",
  "Simi Valley",
  "Concord",
  "Hartford",
  "Kent",
  "Lafayette",
  "Midland",
  "Surprise",
  "Denton",
  "Victorville",
  "Evansville",
  "Santa Clara",
  "Abilene",
  "Athens",
  "Vallejo",
  "Allentown",
  "Norman",
  "Beaumont",
  "Independence",
  "Murfreesboro",
  "Ann Arbor",
  "Springfield",
  "Berkeley",
  "Peoria",
  "Provo",
  "El Monte",
  "Columbia",
  "Lansing",
  "Fargo",
  "Downey",
  "Costa Mesa",
  "Wilmington",
  "Arvada",
  "Inglewood",
  "Miami Gardens",
  "Carlsbad",
  "Westminster",
  "Rochester",
  "Odessa",
  "Manchester",
  "Elgin",
  "West Jordan",
  "Round Rock",
  "Clearwater",
  "Waterbury",
  "Gresham",
  "Fairfield",
  "Billings",
  "Lowell",
  "San Buenaventura",
  "Pueblo",
  "High Point",
  "West Covina",
  "Richmond",
  "Murrieta",
  "Cambridge",
  "Antioch",
  "Temecula",
  "Norwalk",
  "Centennial",
  "Everett",
  "Palm Bay",
  "Wichita Falls",
  "Green Bay",
  "Daly City",
  "Burbank",
  "Richardson",
  "Pompano Beach",
  "North Charleston",
  "Broken Arrow",
  "Boulder",
  "West Palm Beach",
  "Santa Maria",
  "El Cajon",
  "Davenport",
  "Rialto",
  "Las Cruces",
  "San Mateo",
  "Lewisville",
  "South Bend",
  "Lakeland",
  "Erie",
  "Tyler",
  "Pearland",
  "College Station",
  "Kenosha",
  "Sandy Springs",
  "Clovis",
  "Flint",
  "Roanoke",
  "Albany",
  "Jurupa Valley",
  "Compton",
  "San Angelo",
  "Hillsboro",
  "Lawton",
  "Renton",
  "Vista",
  "Davie",
  "Greeley",
  "Mission Viejo",
  "Kennewick",
  "Charleston",
  "Bend",
  "Dearborn",
  "Santa Fe",
  "Tuscaloosa",
  "Livonia",
  "Lawrence",
  "Concord",
  "Cicero",
  "St. George",
  "Apple Valley",
  "Camden",
  "Danbury",
  "San Marcos",
  "Goodyear",
  "Yuma",
  "Redding",
  "Westland",
  "Orem",
  "Layton",
  "Carmel",
  "Kenner",
  "Fishers",
  "Youngstown",
  "Ogden",
  "Passaic",
  "Buena Park",
  "Longview",
  "Boynton Beach",
  "Santa Monica",
  // Add more locations as needed
]

export const postal_codes =[
  "10001", "20001", "30301", "33101", "48201", "60601", "70112", "80202", "90001", "98101",
"11201", "22202", "33301", "44101", "55401", "70116", "80205", "90210", "98109", "20018",
"10010", "22314", "33401", "30339", "60610", "75201", "92101", "90272", "98121", "10022",
"20036", "33602", "60618", "75209", "94102", "90045", "80211", "33139", "11222", "27701",
"10013", "22209", "32801", "60622", "75225", "94110", "90046", "80218", "98119", "11231",
"20024", "33606", "60647", "75240", "94123", "90064", "80220", "98104", "10023", "22201",
"32803", "60657", "75205", "94109", "90034", "80209", "98103", "11215", "20009", "33629",
"60614", "75230", "94117", "90035", "80203", "98102", "10011", "22203", "32804", "60613",
"75220", "94114", "90025", "80212", "98107", "11211", "20005", "33611", "60654", "75219"


];

  
  export const yearsOfProduction = [
    { title: "Select Reviews", value: "" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
  ];
  export const SelectRating = [
    {
      title: "1",
      value: 1,
    },
    {
      title: "2",
      value:2,
    },
    {
      title: "3",
      value: 3,
    },
    {
      title: "4",
      value:4,
    },
    {
      title: "5",
      value:5,
    },
  ];
  export const PriceRange = [
    {
      title: "50k-100k",
      value: 50000_100000,
    },
    {
      title: "101k-250k",
      value:101000_250000,
    },
    {
      title: "251k-500k",
      value: 251000_500000,
    },
    {
      title: "501k-1M",
      value:501000_1000000,
    },
    {
      title: "1M-2M",
      value:1000000_2000000,
    },
  ];
  
  export const fuels = [
    {
      title: "Select price range",
      value: "",
    },
    {
      title: "Fuel",
      value: "Fuel",
    },
    {
      title: "Gas",
      value: "Gas",
    },
    {
      title: "Electricity",
      value: "Electricity",
    },
  ];
  export const transmission = [
    {
      title: "Select fees range",
      value: "",
    },
    {
      title: "Online",
      value: "a",
    },
    {
      title: "Offline",
      value: "m",
    },
    
  ];
  export const drive = [
    {
      title: "Select weeks",
      value: "",
    },
    {
      title: "option1",
      value: "FWD",
    },
    {
      title: "option2",
      value: "RWD",
    },
    
  ];
  export const rating = [
    {
      title:"1",
      value:"1",
    },
    {
      title:"2",
      value:"2",
    },
    {
      title:"3",
      value:"3",
    },
    {
      title:"4",
      value:"4",
    },
    {
      title:"5",
      value:"5",
    },
    
  ]

  export const price =[
    {
      title:"50k-500k",
      value:"50000_500000",
    },
    {
      title:"501k-1m",
      value:"501000_1000000",
    },
    {
      title:"1m-2m",
      value:"1000000_2000000",
    }
  ]


  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
  ]
 // /constants/index.ts

export const newsOutlets = [
  {
    src: '/Abilene.png',
    alt: 'Abilene',
    width: 250,
    height: 150,
  },
  {
    src: '/Informația.png',
    alt: 'Informația',
    width: 250,
    height: 150,
  },
  {
    src: '/Burlington.png',
    alt: 'Burlington',
    width: 250,
    height: 150,
  },
  {
    src: '/TNYT.png',
    alt: 'TNYT',
    width: 250,
    height: 150,
  },
  {
    src: '/Courier.png',
    alt: 'Courier',
    width: 250,
    height: 150,
  },
  {
    src: '/The_Salinas.png',
    alt: 'The Salinas',
    width: 250,
    height: 150,
  },
  {
    src: '/Clarion.png',
    alt: 'Clarion',
    width: 250,
    height: 150,
  },
  {
    src: '/Skagit.png',
    alt: 'Skagit',
    width: 250,
    height: 150,
  },
];

    export const images = [
      {
        id: 1,
        src: "/blog1.png",
        title: "The Ultimate Guide to Choosing the Right Real Estate Agent.",
        desc: "Choosing the right real estate agent can make all the difference in your property buying or selling experience. ",
      },
      {
        id: 2,
        src: "/blog2.png",
        title: "Mastering the Art of Negotiation in Real Estate.",
        desc: "Negotiation is a critical skill when buying or selling a property. As a potential homebuyer or seller, knowing how to negotiate...",
      },
      {
        id: 3,
        src: "/blog3.png",
        title: "Tips for First-Time Homebuyers: Navigating the Real Estate Market.",
        desc: "Buying your first home is an exciting milestone, but it can also be overwhelming. As a first-time homebuyer...",
      },
      {
        id: 4,
        src: "/hero-man.png",
        title: "Latte",
        desc: "A latte or caffè latte is a milk coffee that boasts a silky layer of foam as a real highlight to the drink. A true latte will be made up of one or two shots of espresso, steamed milk and a final, thin layer of frothed milk on top",
      },
      {
        id: 5,
        src: "/hero.png",
        title: "Macchiato",
        desc: "Caffè macchiato, sometimes called espresso macchiato, is an espresso coffee drink with a small amount of milk, usually foamed. ",
      },
    ];
    
    // /constants/findings.ts

export const findings = [
  {
    id: 1,
    iconSrc: '/mag.svg',
    title: 'Search Agents',
    description:
      'Enter your city, town or postcode in our user friendly search bar to explore the top real estate agents in your area.',
  },
  {
    id: 2,
    iconSrc: '/profile.svg',
    title: 'Compare Agents',
    description:
      'View agent profiles, read reviews, and compare metrics side by side to narrow down your options.',
  },
  {
    id: 3,
    iconSrc: '/profileplus.svg',
    title: 'Connect with Agent',
    description:
      'Once you\'ve found your ideal match, connect with the agent directly through TRACH and start your real estate journey with confidence.',
  },
];
